name: Create ui-kit release artifact and publish to ComfyUI registry

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Build project
        id: build
        env:
          "NEXT_PUBLIC_DEV": "false"
        run: |
          mkdir -p releases/
          cur_dir="$(pwd)"
          cd ui/
          npm ci
          npm run build
          dist_dir="../nodes/web/static/"
          cd "$dist_dir"
          dist_file_full="${cur_dir}/releases/comfystream-uikit.zip"
          zip -DTr9q "${dist_file_full}" ./
          echo "dist_file=${dist_file_full}" >> $GITHUB_OUTPUT
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: releases/

      - name: Create release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build.outputs.dist_file }}
          make_latest: true
          generate_release_notes: true

  publish-comfyui-node:
    name: Publish Custom Node to ComfyUI registry
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@v1
        with:
          ## Add your own personal access token to your Github Repository secrets and reference it here.
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
